### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by ConsenSys-Academy** [artemgalimzyanov/blockchain-developer-bootcamp-final-project#1]
Hi @artemgalimzyanov – Congratulations, your Final Project passed! We'll be approving it on the course itself in a week or two, but here's your feedback in the meanwhile:

### Frontend

- Really straightforward frontend allows for clear organization, that's great UX
- Appreciate the errors for failed or incorrect submissions on forms, super helpful for the user to get that feedback
- Only submitted steps, but it's a fun frontend for the project!

### Design and Security

- Good straightforward use of `Ownable` and inheritance. Nice that it doesn't prevent a user who's not the owner from interacting with the contract and frontend.
- Great start on basic security coverage.
- Modifiers are great for validation, nice security feature

### Testing

- Nice use of `truffle develop` to sidestep having the user run a separate ganache-cli component
- Your clean setup of variables for the tests really helps someone who’s just reading the contract

### Overall

- Great idea for a dapp, love the nature of connecting public blockchains and physical health!
- You did an awesome job implementing this project. I can tell you spent a lot time by the way in which all the different elements come together. Hope you enjoyed the learning journey so far and can continue building on this.

**Comment by artemgalimzyanov** [comment]
Thank you very much for your support and valuable feedback
